### ISSUE TITLE
Modify config.json can not work in macOS Catalina.

### ISSUE THREAD

**Issue by lanceylai** [fallroot/copy-url-for-alfred#10]
I modify the config.json file, but it does not work.

**Comment by frankgaillard** [comment]
Hi fallroot. 

Excellent script. Thank you. 

I too have tried to edit config.json to add another custom format but despite saving it, I can't seem to make changes appear in Alfred. Similarly, changing the default configs does not seem to do anything. I am 100% sure this is something obvious that I should be doing, but if you could point me in the right direction it would be much appreciated. 

At the end of config I have added the following: 

`,
  {
    "format": "Gmail:${url}",
    "title": "Gmail"
  }
]`

**Comment by fallroot** [comment]
Try to edit the file in `~/Library/Application Support/Alfred/Workflow Data/com.fallroot.copyurl/config.json` not in the path that this workflow was installed.

**Comment by frankgaillard** [comment]
Hi Fallroot. I knew it would be something I was missing.  Thank you. Works perfectly.
