### ISSUE TITLE
Copy URL from Clipboard

### ISSUE THREAD

**Issue by miguelpuyol** [fallroot/copy-url-for-alfred#2]
Hi! I really like your workflow.

Would it be too hard to add a functionality to generate the snippets from the clipboard too?

Thanks

**Comment by fallroot** [comment]
Thanks for your comment.  This workflow needs both url and title. But what I can take from clipboard is either one. Other app or workflow may be suitable for your use.

**Comment by miguelpuyol** [comment]
Thanks for your response. I was thinking that the title could be added as
an Alfred parameter after 'url'.

I might try to do it myself and ask for a PR

On Wednesday, 9 March 2016, CK Moon notifications@github.com wrote:

> Thanks for your comment. This workflow needs both url and title. But what
> I can take from clipboard is either one. Other app or workflow may be
> suitable for your use.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fallroot/copy-url-for-alfred/issues/2#issuecomment-194150803
> .

## 

Miguel García Puyol
