### ISSUE TITLE
Doesn’t work for Firefox

### ISSUE THREAD

**Issue by khalidl** [fallroot/copy-url-for-alfred#5]
I love this workflow and use it multiple times a day with Chrome. I’m considering switching to Firefox and was wondering if it is possible to make it work with it. Tried my hand at it, but didn’t succeed unfortunately.

**Comment by kw-lee** [comment]
I am an user of Vivaldi browser. I just sent a PR: [Support selection text in Vivaldi by heleeos · Pull Request #6 · fallroot/copy-url-for-alfred](https://github.com/fallroot/copy-url-for-alfred/pull/6) to make this workflow works for Vivaldi browser. I think you can do this for Firefox.

**Comment by fallroot** [comment]
@khalidl I'm sorry for late reply. This workflow was made by using Open Scripting Architecture that many application supports in macos. Unfortunately Firefox does not supply this feature yet so I can't get the url and title of current page.
