### ISSUE TITLE
Adding support to Brave browser.

### ISSUE THREAD

**Issue by politicus** [fallroot/copy-url-for-alfred#7]
Hi! 

Really nice workflow, thanks for sharing. 

Any plan on adding Brave support ? 

I stopped using Google Chrome few months ago as I found it getting slower and slower and would love to ba able to use your workflow too.

**Comment by fallroot** [comment]
I am sorry but I have no plan for minor browsers. If the browser supports Open Scripting Architecture, you could fork this repository and try your favorite browser by adding some codes in ease like #6. Chromium based browsers will work maybe.

**Comment by fallroot** [comment]
I just deployed [new version](https://github.com/fallroot/copy-url-for-alfred/releases/tag/0.1.0) for supporting Chromium based browsers.
If you want to add your favorite browser, follow [this steps](https://github.com/fallroot/copy-url-for-alfred#add-your-favorite-browsers).
