### ISSUE TITLE
copy title and url to clipboard

### ISSUE THREAD

**Issue by BeeryHolstein** [fallroot/copy-url-for-alfred#8]
With Alfred 3.8.2 how do I copy into the clipboard a line with title and url e.g. 

> New Issue - https://github.com/fallroot/copy-url-for-alfred/issues/new

**Comment by fallroot** [comment]
In the service or editor which supports markdown format like github, `> ${title} - ${url}` format will work.
If supports html format, you should write html codes like `<blockquote sytle="border-left: 0.25em solid #dfe2e5;padding-left:1em">${title} - <a href=\"${url}\">${title}</a></blockquote>`
